# Generated by Django 3.2.4 on 2021-06-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210604_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
